language: node_js
node_js:
  - "0.10"
branches:
  only:
  - master
before_install:
  - gem update --system
  - gem install sass
  - npm install -g grunt-cli
install: npm install
before_script: grunt build
after_success:
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy git@github.com:tompekay/tompekay.github.io.git
  - git push deploy
